import { API_BASE } from './runtime.js';
import { icon } from './icons.js';
import { io } from './vendor/socket.io.esm.min.js';
import {initInstall,installControl} from './pwa.js';
import {helpControls} from './help.js';
export { icon,API_BASE };
export const $=(s,root=document)=>root.querySelector(s),$$=(s,root=document)=>[...root.querySelectorAll(s)];
export const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const S={config:null,catalog:{},user:null,token:sessionStorage.getItem('gymfit-token')||'',live:false};
export const allowed=permission=>S.user?.permissions.includes('*')||S.user?.permissions.includes(permission);
export function workspaceTools(module){const role=document.body.classList.contains('admin')?'admin':document.body.classList.contains('trainer')?'trainer':'member';return installControl()+helpControls({role,module,permissions:S.user?.permissions||[],features:S.config.modules,branding:S.config.branding},modal,E);}
export function enhanceUI(){for(const table of $$('table')){const labels=$$('thead th',table).map(th=>th.textContent.trim());table.classList.add('mobile-cards');$$('tbody tr',table).forEach(row=>$$('td',row).forEach((td,index)=>td.dataset.label=labels[index]||''));}$$('[data-avatar]').forEach(el=>el.loading='lazy');$$('nav a').forEach(a=>a.setAttribute('aria-current',a.classList.contains('active')?'page':'false'));$$('.pill,.settings-nav button').forEach(b=>b.setAttribute('aria-pressed',String(b.classList.contains('active'))));}
document.addEventListener('click',event=>{const tab=event.target.closest('.pill,.settings-nav button');if(tab&&!tab.disabled){[...tab.parentElement.children].forEach(b=>{b.classList.toggle('active',b===tab);b.setAttribute('aria-pressed',String(b===tab));});}const link=event.target.closest('nav a[href^="#"]');if(link){$$('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href').split('?')[0]===link.getAttribute('href').split('?')[0]));$('.sidebar')?.classList.remove('open');$('.drawer-backdrop')?.classList.remove('open');}},true);
let socket,refresh,toastTimer;
export function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),4500);}
export const asset=value=>{if(!value)return '';if(/^\/api\/pwa-icon\/\d+\/192\.png$/.test(value))return API_BASE+value;if(value.startsWith('/media/'))return API_BASE+value;if(/^assets\/[\w/.-]+$/.test(value))return new URL(value,document.baseURI).href;return '';};
export const cover=r=>asset(r?.media?.find(m=>m.cover)?.url||r?.media?.[0]?.url||r?.data?.image||S.config?.branding.hero);
export const money=(amount,currency=S.config?.operations.currency)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:currency||'PHP',maximumFractionDigits:2}).format(Number(amount||0)/100);
export const dateTime=(value,options={dateStyle:'medium',timeStyle:'short'})=>value?new Intl.DateTimeFormat('en-PH',{timeZone:S.config?.operations.timezone||'Asia/Manila',...options}).format(new Date(value)):'—';
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:S.config?.operations.timezone||'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const status=v=>`<span class="badge ${['active','approved','confirmed','completed','sent','online'].includes(v)?'good':['rejected','cancelled','expired','failed','no_show'].includes(v)?'bad':'warm'}">${E(String(v||'').replaceAll('_',' '))}</span>`;
export const empty=(title,body='',i='dumbbell')=>`<div class="empty">${icon(i,32)}<h3>${E(title)}</h3><p>${E(body)}</p></div>`;
export const button=(text,action,cls='primary',i='')=>`<button class="btn ${cls}" data-action="${action}">${i?icon(i):''}${E(text)}</button>`;
export const brand=()=>`<a class="brand" href="index.html"><img src="${asset(S.config.branding.logo)}" alt=""><span><b>${E(S.config.branding.name)}</b><small>${E(S.config.branding.tagline)}</small></span></a>`;
export const avatar=(user=S.user)=>user?.avatarId?`<img class="avatar" src="${asset(S.config.branding.pwaIcon)}" data-avatar="${user.avatarId}" alt="${E(user.name)}">`:`<span class="avatar initials">${E((user?.name||'You').split(' ').slice(0,2).map(v=>v[0]).join(''))}</span>`;
export async function api(path,options={}){
 const headers={...(S.token?{Authorization:`Bearer ${S.token}`}:{})};const body=options.body;
 if(body!==undefined&&!(body instanceof FormData)&&!(body instanceof Blob)){headers['Content-Type']='application/json';options={...options,body:JSON.stringify(body)};}
 if(options.idempotent)headers['Idempotency-Key']=options.key||crypto.randomUUID();
 let response;try{response=await fetch(API_BASE+path,{...options,headers:{...headers,...options.headers},cache:'no-store',signal:options.signal||AbortSignal.timeout(25000)});}catch{throw new Error('Could not reach your gym. Check your connection and try again.');}
 if(!response.ok){let data;try{data=await response.json();}catch{}if(response.status===401&&S.token){S.token='';S.user=null;sessionStorage.removeItem('gymfit-token');socket?.disconnect();}throw new Error(data?.error||'We could not complete this action.');}
 if(options.binary)return {blob:await response.blob(),filename:response.headers.get('Content-Disposition')?.match(/filename="([^"]+)"/)?.[1]};return response.json();
}
export function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
export function modal(title,html,onSubmit){const dialog=$('#modal');dialog.innerHTML=`<form method="dialog" class="modal-head"><h2>${E(title)}</h2><button class="icon-btn" aria-label="Close">${icon('close')}</button></form>${html}`;dialog.showModal();if(onSubmit){const f=$('form[data-form]',dialog);f?.addEventListener('submit',async e=>{e.preventDefault();const b=$('[type=submit]',f);b.disabled=true;try{await onSubmit(new FormData(f),f);dialog.close();await refresh?.();}catch(error){toast(error.message);}finally{b.disabled=false;}});}return dialog;}
export function field(label,name,value='',type='text',extra=''){return `<label class="field"><span>${E(label)}</span><input type="${type}" name="${name}" value="${E(value)}" ${extra}></label>`;}
export function select(label,name,options,value='',extra=''){return `<label class="field"><span>${E(label)}</span><select name="${name}" ${extra}>${options.map(([id,text])=>`<option value="${E(id)}" ${String(id)===String(value)?'selected':''}>${E(text)}</option>`).join('')}</select></label>`;}
export function textarea(label,name,value='',extra=''){return `<label class="field"><span>${E(label)}</span><textarea name="${name}" ${extra}>${E(value)}</textarea></label>`;}
export function toggle(label,name,value){return `<label class="toggle"><span>${E(label)}</span><input name="${name}" type="checkbox" ${value?'checked':''}></label>`;}
export const submit=(text='Save changes')=>`<div class="form-foot"><button type="submit" class="btn primary">${E(text)}</button></div>`;
export async function boot(role,onRefresh){refresh=onRefresh;try{await syncConfig();if(S.token)try{S.user=await api('/api/auth/me');}catch{}await initPWA(role);await connect();return true;}catch(e){$('#app').innerHTML=`<main class="offline">${empty('Your gym is currently offline',e.message,'refresh')}${button('Try again','retry','primary','refresh')}</main>`;$('[data-action=retry]').onclick=()=>location.reload();return false;}}
export async function syncConfig(){const [config,catalog]=await Promise.all([api('/api/config'),api('/api/catalog')]);S.config=config;S.catalog=catalog;const b=config.branding;document.title=b.name+(document.body.classList.contains('admin')?' · Management':document.body.classList.contains('trainer')?' · Trainer':'');const style=document.documentElement.style;for(const [css,key] of [['--accent','accent'],['--orange','secondaryAccent'],['--bg','background'],['--surface','surface']])style.setProperty(css,b[key]);$('meta[name=theme-color]').content=b.background;$('link[rel=icon]').href=asset(b.favicon);$('link[rel=apple-touch-icon]').href=asset(b.pwaIcon);}
async function initPWA(role){await initInstall(role,S.config,asset,modal);}
export const canPush=()=>Boolean(S.config?.vapidPublicKey&&'PushManager' in window&&'Notification' in window&&'serviceWorker' in navigator);
export async function pushEnable(){if(!S.config.vapidPublicKey)throw new Error('The gym team has not connected push notifications yet.');if(!('PushManager'in window))throw new Error('Install this app on your home screen to use notifications.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notifications are not allowed. You can enable them in browser settings.');const registration=await navigator.serviceWorker.ready;const key=S.config.vapidPublicKey.replace(/-/g,'+').replace(/_/g,'/');const bytes=Uint8Array.from(atob(key),c=>c.charCodeAt(0));const existing=await registration.pushManager.getSubscription();const subscription=existing||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});await api('/api/push/subscribe',{method:'POST',body:subscription.toJSON()});toast('Push notifications enabled.');}
export async function connect(){if(socket)socket.disconnect();try{socket=io(API_BASE,{auth:{token:S.token},transports:['websocket','polling'],reconnection:true});socket.on('connect',()=>{S.live=true;if(S.user)refresh?.();updateLive();});socket.on('disconnect',()=>{S.live=false;updateLive();});socket.on('connect_error',()=>{S.live=false;updateLive();});for(const ev of ['settingsUpdated','brandingUpdated','catalogUpdated','scheduleUpdated','bookingUpdated','membershipUpdated','paymentUpdated','profileUpdated','memberUpdated','fitnessUpdated','checkinUpdated','notificationUpdated','messageUpdated','systemUpdated'])socket.on(ev,async()=>{try{if(['settingsUpdated','brandingUpdated','catalogUpdated'].includes(ev)){await syncConfig();await initPWA(document.body.className.includes('admin')?'admin':document.body.className.includes('trainer')?'trainer':'member');}if(ev==='profileUpdated'&&S.token)S.user=await api('/api/auth/me');await refresh?.();}catch{}});}catch{S.live=false;}}
function updateLive(){$$('[data-live]').forEach(el=>{el.innerHTML=`<span class="dot ${S.live?'':'off'}"></span>${S.live?'Live':'Reconnecting'}`;});}
export async function resolveAvatars(){for(const img of $$('[data-avatar]'))try{const data=await api(`/api/media-info/${img.dataset.avatar}`);img.src=asset(data.thumbnail);}catch{img.removeAttribute('src');}}
export async function logout(){let endpoint='';try{const registration=await navigator.serviceWorker?.getRegistration();const subscription=await registration?.pushManager?.getSubscription();if(subscription){endpoint=subscription.endpoint;await subscription.unsubscribe();}}catch{}try{await api('/api/auth/logout',{method:'POST',body:{endpoint}});}catch{}S.token='';S.user=null;sessionStorage.removeItem('gymfit-token');socket?.disconnect();await connect();await refresh?.();}
export function loginModal(register=false,{trial=false}={}){
 modal(register?(trial?'Start your gym trial':'Start your next chapter'):'Welcome back',`<form data-form class="form">${trial?`<p class="hint">Register your interest in a ${S.config.operations.trialDays}-day trial. The gym team will contact you to arrange your visit.</p>`:''}${register?field('Full name','name','','text','required autocomplete="name"')+field('Mobile number','phone','','tel','autocomplete="tel"'):''}${field('Email address','email','','email','required autocomplete="email"')}${field('Password','password','','password',`required minlength="12" autocomplete="${register?'new-password':'current-password'}"`)}${register?`<label class="checkbox"><input type="checkbox" name="terms" required><span>I agree to the <button type="button" class="text-btn" data-legal="terms">gym terms</button> and <button type="button" class="text-btn" data-legal="privacy">privacy policy</button>.</span></label>`:''}${submit(register?'Create account':'Sign in')}<p class="hint">${register?'Already a member?':'New here?'} <button type="button" class="text-btn" id="auth-switch">${register?'Sign in':'Create account'}</button></p></form>`,async(fd)=>{const result=await api('/api/auth/'+(register?'register':'login'),{method:'POST',body:{name:fd.get('name'),email:fd.get('email'),phone:fd.get('phone'),password:fd.get('password'),terms:fd.has('terms'),trial:register&&trial}});S.token=result.token;S.user=result.user;sessionStorage.setItem('gymfit-token',result.token);await connect();});$('#auth-switch').onclick=()=>{ $('#modal').close();loginModal(!register,{trial});};$$('[data-legal]').forEach(b=>b.onclick=()=>{const kind=b.dataset.legal;const content=S.config.branding[kind];let box=$('#legal-copy');if(!box){box=document.createElement('div');box.id='legal-copy';box.className='legal-copy';$('.form',$('#modal')).appendChild(box);}box.textContent=content;});
}
export function profileModal(){modal('Your profile',`<form data-form class="form"><div class="profile-photo">${avatar()}<label class="btn secondary">${icon('image')} Change photo<input type="file" name="avatar" accept="image/*" capture="user" hidden></label></div><div id="photo-preview"></div>${field('Full name','name',S.user.name,'text','required')}${field('Mobile number','phone',S.user.phone,'tel')}${toggle('Email notifications','email',S.user.preferences.email)}${toggle('SMS notifications','sms',S.user.preferences.sms)}${toggle('Push notifications','push',S.user.preferences.push)}${S.user.role==='Member'?select('Fitness goal','goal',[['general','Stay active'],['strength','Build strength'],['fitness','Improve fitness']],S.user.preferences.goal||'general')+select('Experience','experience',[['beginner','Beginner'],['intermediate','Intermediate'],['experienced','Experienced']],S.user.preferences.experience||'beginner')+field('Preferred workout length (minutes)','workoutMinutes',S.user.preferences.workoutMinutes||45,'number','min="15" max="180" required'):''}${textarea('Dietary preferences','dietary',S.user.preferences.dietary||'')}${submit()}</form>`,async(fd)=>{S.user=await api('/api/auth/profile',{method:'PUT',body:{name:fd.get('name'),phone:fd.get('phone'),preferences:{email:fd.has('email'),sms:fd.has('sms'),push:fd.has('push'),dietary:fd.get('dietary'),...(S.user.role==='Member'?{goal:fd.get('goal'),experience:fd.get('experience'),workoutMinutes:Number(fd.get('workoutMinutes'))}:{})}}});const file=fd.get('avatar');if(file?.size){let uploadFile=file;const crop=$('#crop-canvas');if(crop)uploadFile=await new Promise(resolve=>crop.toBlob(b=>resolve(new File([b],'avatar.jpg',{type:'image/jpeg'})),'image/jpeg',.9));const data=new FormData();data.append('file',uploadFile);const r=await api('/api/auth/avatar',{method:'POST',body:data});S.user=r.user;}toast('Profile updated.');});
 const input=$('[name=avatar]');input.onchange=async()=>{const file=input.files[0];if(!file)return;try{const bitmap=await createImageBitmap(file);$('#photo-preview').innerHTML='<canvas id="crop-canvas" width="512" height="512"></canvas><label class="field"><span>Adjust crop</span><input id="crop-zoom" type="range" min="1" max="3" value="1" step="0.01"></label><p class="hint">Drag the photo to position it, then save.</p>';const canvas=$('#crop-canvas'),ctx=canvas.getContext('2d');let zoom=1,dx=0,dy=0,drag;const paint=()=>{const scale=Math.max(512/bitmap.width,512/bitmap.height)*zoom,w=bitmap.width*scale,h=bitmap.height*scale;dx=Math.max(-(w-512)/2,Math.min((w-512)/2,dx));dy=Math.max(-(h-512)/2,Math.min((h-512)/2,dy));ctx.clearRect(0,0,512,512);ctx.drawImage(bitmap,(512-w)/2+dx,(512-h)/2+dy,w,h);};paint();$('#crop-zoom').oninput=e=>{zoom=Number(e.target.value);paint();};canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,dx,dy};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(drag){const scale=512/canvas.getBoundingClientRect().width;dx=drag.dx+(e.clientX-drag.x)*scale;dy=drag.dy+(e.clientY-drag.y)*scale;paint();}};canvas.onpointerup=()=>drag=null;}catch{toast('Crop preview is unavailable. The server will optimize your photo when saved.');}};
}
export async function showNotifications(){const rows=await api('/api/notifications');modal('Your notifications',`<div class="notification-list">${rows.length?rows.map(n=>`<button class="notification ${n.read_at?'':'unread'}" data-read="${n.id}"><span class="icon-circle">${icon('bell')}</span><span><b>${E(n.title)}</b><p>${E(n.body)}</p><small>${dateTime(n.created_at)}</small></span></button>`).join(''):empty('You’re all caught up','Your gym updates will appear here.','bell')}</div>`);$$('[data-read]').forEach(b=>b.onclick=async()=>{await api(`/api/notifications/${b.dataset.read}/read`,{method:'POST',body:{}});b.classList.remove('unread');});}
export async function showReceipt(id){const data=await api(`/api/payments/${id}/receipt`),p=data.payment,b=data.branding;modal('Payment receipt',`<article class="receipt" id="receipt"><div class="receipt-brand"><img src="${asset(b.logo)}" alt=""><h2>${E(b.name)}</h2></div><p>${E(b.address)}</p><h3>PAYMENT RECEIPT #${p.id}</h3>${status(p.status)}<dl><dt>Member</dt><dd>${E(p.member_name)}</dd><dt>Amount</dt><dd>${money(p.amount,data.currency)}</dd><dt>Payment method</dt><dd>${E(p.method_name)}</dd><dt>Reference</dt><dd>${E(p.reference||'—')}</dd><dt>Date</dt><dd>${dateTime(p.reviewed_at||p.created_at)}</dd></dl><p>${E(b.receiptFooter)}</p><small>${E(b.email)} ${E(b.phone)}</small></article><button id="print-receipt" class="btn primary">${icon('download')} Print / Save PDF</button>`);$('#print-receipt').onclick=()=>window.print();}
export async function previewProof(id){const {blob}=await api(`/api/private-proof/${id}`,{binary:true});const url=URL.createObjectURL(blob);modal('Uploaded payment proof',blob.type==='application/pdf'?`<iframe class="proof" src="${url}" title="Payment proof"></iframe>`:`<img class="proof-image" src="${url}" alt="Uploaded payment proof">`);$('#modal').addEventListener('close',()=>URL.revokeObjectURL(url),{once:true});}
export function errorBoundary(fn){return async(...args)=>{try{return await fn(...args);}catch(e){toast(e.message);}};}
window.addEventListener('online',()=>{syncConfig().then(()=>refresh?.()).catch(()=>{});});window.addEventListener('focus',()=>{if(S.config)refresh?.().catch?.(()=>{});});
