const CACHE='gymfit-shell-v2.0.0';
const SHELL=['./','./index.html','./admin.html','./trainer.html','./manifest.webmanifest','./admin-manifest.webmanifest','./trainer-manifest.webmanifest','./css/app.css','./js/runtime.js','./js/core.js','./js/pwa.js','./js/help.js','./js/coach-ui.js','./js/icons.js','./js/member.js','./js/admin.js','./js/trainer.js','./js/vendor/socket.io.esm.min.js','./assets/logo.svg','./assets/icons/icon-192.png','./assets/icons/icon-512.png','./assets/fonts/manrope-latin.woff2','./assets/fonts/sora-latin.woff2',...['strength','classes','training','nutrition','facility'].map(n=>`./assets/default-heroes/${n}.webp`)];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL)));self.skipWaiting();});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith('gymfit-shell-')&&key!==CACHE)await caches.delete(key);await self.clients.claim();})());});
self.addEventListener('fetch',event=>{
 const request=event.request,url=new URL(request.url);
 if(request.method!=='GET'||url.origin!==self.location.origin||request.headers.has('Authorization')||/\/(api|media|socket\.io)(\/|$)/.test(url.pathname))return;
 const allowed=new Set(SHELL.map(p=>new URL(p,self.registration.scope).href));const normalized=new URL(url.href);normalized.search='';normalized.hash='';if(!allowed.has(normalized.href))return;
 if(normalized.pathname.endsWith('.webmanifest')){event.respondWith((async()=>{return (await caches.match(normalized.href))||fetch(request);})());return;}
 event.respondWith((async()=>{try{const response=await fetch(request,{cache:'no-cache'});if(response.ok){const cache=await caches.open(CACHE);await cache.put(normalized.href,response.clone());}return response;}catch{return (await caches.match(normalized.href))||Response.error();}})());
});
self.addEventListener('push',event=>{let data;try{data=event.data.json();}catch{return;}event.waitUntil(self.registration.showNotification(data.title,{body:data.body,icon:data.icon,tag:data.tag,renotify:false,data:{url:data.url}}));});
self.addEventListener('notificationclick',event=>{event.notification.close();const target=new URL(event.notification.data?.url||'./index.html',self.registration.scope);if(target.origin!==new URL(self.registration.scope).origin)return;event.waitUntil((async()=>{const windows=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const window of windows){if(new URL(window.url).origin===target.origin){await window.navigate(target.href);return window.focus();}}return self.clients.openWindow(target.href);})());});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();if(event.data?.type==='BRANDING_MANIFESTS'){event.waitUntil((async()=>{const cache=await caches.open(CACHE);for(const filename of ['manifest.webmanifest','admin-manifest.webmanifest','trainer-manifest.webmanifest']){const manifest=event.data.manifests?.[filename];if(!manifest)continue;const scope=new URL(self.registration.scope);if(new URL(manifest.start_url).origin!==scope.origin||!manifest.start_url.startsWith(scope.href)||manifest.scope!==scope.href)continue;await cache.put(new URL(filename,scope).href,new Response(JSON.stringify(manifest),{headers:{'Content-Type':'application/manifest+json'}}));}event.ports[0]?.postMessage({ok:true});})());}});
